### PR TITLE
Update readme with TS typings

### PR DESCRIPTION
**Pull request by ondrowan**
Those might be needed for users that compile TS with `noImplicitAny` compiler option.

### CODE REVIEW

**Comment by gpahal** [comment]
Did you need these typings anywhere?

**Comment by ondrowan** [comment]
I use TypeScript with `strict` compiler option (which includes `noImplicitAny`). In that case, if typing isn't present, you get the following error:

```
Could not find a declaration file for module 'protobufjs'. '.../node_modules/protobufjs/dist/protobuf.js' implicitly has an 'any' type.
 Try `npm install @types/protobufjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'protobufjs';`
```

**Comment by gpahal** [comment]
Oh! I see. BTW thanks for the contribution.

**Comment by gpahal** [comment]
Could you add a command for yarn also and the `save-dev` option for both of them.

**Comment by ondrowan** [comment]
Done.

**Review by gpahal — APPROVED** [review]

**Comment by gpahal** [comment]
Thanks

**Pull request merged**
